### PR TITLE
feat: add JDK8 and use it as default

### PR DESCRIPTION
**Pull request by dduportal**
Signed-off-by: Damien Duportal <damien.duportal@gmail.com>

### CODE REVIEW

**Review by timja — COMMENTED** [review]
why?

**Comment by lemeurherve** [comment]
In case we've encounter problem during the next weekly release, this pr in combination to the "one container" one will allow to retry with the new pipeline but with the same jdk version as the one in the current pr if needed.

**Comment by timja** [comment]
Packaging doesn't use `java` outside of the inbound agent as far as I know.

Can't really see this being an issue and would prob just switch 11 to 8 if so rather than this complexity

**Comment by lemeurherve** [comment]
Damien will certainly have a better answer, I'm probably missing details here

**Comment by dduportal** [comment]
As @lemeurherve said:

> First quick response: in case we've encounter problem during the next weekly release, this pr in combination to the "one container" one will allow to retry with the new pipeline but with the same jdk version as the one in the current weekly pipeline if needed.

This is a discussion with  Wadeck summarized here: https://github.com/jenkins-infra/release/pull/203#issuecomment-1006654153 for reminder.

Last weekly / LTS were built using JDK8. No one minds to use JDK1 for future release, but delivering a security release with an untested change of JDK for compiling is not what one expect.

It costs nothing to delay that change to the weekly right after.

**Comment by timja** [comment]
Isn’t this packaging though not release? Unless they use the same image?

**Comment by timja** [comment]
and they don't https://github.com/jenkins-infra/release/blob/833c03a28a04e8179b425bf4352259b5ba870ec7/PodTemplates.d/release-linux.yaml#L36

so this shouldn't be needed but I guess can leave it open till the release

**Comment by dduportal** [comment]
The idea is to split https://github.com/jenkins-infra/release/pull/203 into sub-PRs:

- Its scope would be narrowed to "switch from 2 container to a single one" so it can be merged in emergency if the release step fails (low probability as the pipeline is really simple and it did not fail last week). It means that is has to be updated to use the image version of docker-packaging generated by the PR here (+ adding the  JENKINS_JAVA_BIN env var to the pod definition to ensure that agent uses JDK11 while keeping JDK8 as default).
- Another PR should be opened in https://github.com/jenkins-infra/release to change the image version, later to cover https://github.com/jenkins-infra/release/issues/199 (which means removing JDK8 from the image


Ideally, we don't have anything to do (hence the draft status ofr the PRs in https://github.com/jenkins-infra/release)  and we can merge all of the change before the weekly of the 18th.

But better safe than sorry, backing the security team with intermediate alternatives is a good thing as well given the amount of work they are doing for the 12th release. (and splitting PR is easier for future self when we'll ask ourselves why did we do that)

**Pull request merged**
