### PR TITLE
Use a UTF-8 locale

### PR DESCRIPTION
**Pull request by timja**
Currently without the fix to see the tests failing

### CODE REVIEW

**Review by MarkEWaite — APPROVED** [review]

**Comment by timja** [comment]
Build is incredibly slow, but looks like it won't abort the previous one.

I can't test this locally though as it's very amd64 heavy

**Comment by timja** [comment]
Ah damn:

```
Error: error in setup: Tar driver is unable to process commands, please use a different driver
```

Probably can't do a test that checks it properly then

**Comment by halkeye** [comment]
DM me and I can spin you up a high powered VM if you want

**Review by MarkEWaite — APPROVED** [review]

**Review by dduportal — COMMENTED** [review]
LGTM

**Pull request merged**
